/**:
  um982_node:
    ros__parameters:
    
      port:
        gnss: /dev/UM982
        gnss_baudrate: 115200
        rtcm: /dev/UM982-RTCM
        rtcm_baudrate: 115200
      
      heading_offset: 0.0